### ISSUE TITLE
DATA_LIST = np.array(DATA_LIST)

### ISSUE THREAD

**Issue by YunBAI-PSL** [finlay-liu/kaggle_public#3]
情感分类中，DATA_LIST = np.array(DATA_LIST)这一步会报错ValueError: setting an array element with a sequence，因为DATA_LIST原本是‘字符串+array’的形式，因此就不能再array了，不知道这个问题怎么解决，有大佬指点一下吗/

**Comment by finlay-liu** [comment]
DATA_LIST = np.array(DATA_LIST, dtype=object)

这样就行。
